import home1 from "../images/home1.jpg";
import home2 from "../images/home2.jpg";
import home3 from "../images/home3.jpg";
import home4 from "../images/home4.jpg";
import hotel1 from "../images/hotel1.jpg";
import hotel2 from "../images/hotel2.jpg";
import hotel3 from "../images/hotel3.jpg";
import hotel4 from "../images/hotel4.jpg";
import villa1 from "../images/villa1.jpg";
import villa2 from "../images/villa2.jpg";
import villa3 from "../images/villa3.jpg";
import villa4 from "../images/villa4.jpg";
import villa5 from "../images/villa5.jpg";
import jphome1 from "../images/jphome1.jpg";
import jphome2 from "../images/jphome2.jpg";
import jphome3 from "../images/jphome3.jpg";
import jphotel1 from "../images/jphotel1.jpg";
import jphotel2 from "../images/jphotel2.jpg";

export const dummyDataList = [
  {
    id: 1,
    title: "Bavery",
    location: "UK",
    category: "House",
    date: "1-10",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 2,
    title: "Palm Harbor",
    location: "UK",
    category: "Villa",
    date: "20-31",
    discription: "2776 Green valley, Highland",
    rooms: "3",
    bathrooms: "1",
    area: "5x5 sq.ft",
    price: "$1000-$2000",
    image: villa1,
  },
  {
    id: 3,
    title: "Faulkner Ave",
    location: "UK",
    category: "Hotel",
    date: "10-20",
    discription: "2776 Green valley, Highland",
    rooms: "2",
    bathrooms: "2",
    area: "6x5 sq.ft",
    price: "$2000-$2500",
    image: hotel1,
  },
  {
    id: 4,
    location: "US",
    title: "Ear rings",
    category: "House",
    date: "1-10",
    discription: "2776 Green valley, Highland",
    rooms: "5",
    bathrooms: "4",
    area: "8x5 sq.ft",
    price: "$500-$1000",
    image: home2,
  },
  {
    id: 5,
    title: "Ear rings",
    location: "US",
    category: "Hotel",
    date: "10-20",
    discription: "2776 Green valley, Highland",
    rooms: "2",
    bathrooms: "1",
    area: "2x6 sq.ft",
    price: "$1000-$2000",
    image: hotel2,
  },
  {
    id: 6,
    title: "Ear rings",
    location: "US",
    category: "Villa",
    date: "20-31",
    discription: "2776 Green valley, Highland",
    rooms: "6",
    bathrooms: "3",
    area: "3x7 sq.ft",
    price: "$2000-$2500",
    image: villa2,
  },
  {
    id: 7,
    title: "Ear rings",
    location: "Japan",
    category: "House",
    date: "1-10",
    discription: "2776 Green valley, Highland",
    rooms: "4",
    bathrooms: "4",
    area: "4x9 sq.ft",
    price: "$500-$1000",
    image: jphome1,
  },
  {
    id: 8,
    title: "Ear rings",
    location: "Japan",
    category: "Hotel",
    date: "10-20",
    discription: "2776 Green valley, Highland",
    rooms: "3",
    bathrooms: "2",
    area: "5x8 sq.ft",
    price: "$1000-$2000",
    image: jphotel1,
  },
  {
    id: 9,
    title: "Ear rings",
    location: "Japan",
    date: "1-10",
    category: "Villa",
    discription: "2776 Green valley, Highland",
    rooms: "3",
    bathrooms: "2",
    area: "5x8 sq.ft",
    price: "$2000-$2500",
    image: villa3,
  },
  {
    id: 10,
    title: "Ear rings",
    location: "Japan",
    category: "House",
    date: "20-31",
    discription: "2776 Green valley, Highland",
    rooms: "5",
    bathrooms: "4",
    area: "4x9 sq.ft",
    price: "$2000-$2500",
    image: jphome2,
  },
  {
    id: 11,
    title: "Ear rings",
    location: "Japan",
    category: "House",
    date: "20-31",
    discription: "2776 Green valley, Highland",
    rooms: "6",
    bathrooms: "4",
    area: "4x9 sq.ft",
    price: "$2500-$3000",
    image: jphome3,
  },
  {
    id: 12,
    title: "Ear rings",
    location: "Japan",
    category: "Hotel",
    date: "1-10",
    discription: "2776 Green valley, Highland",
    rooms: "4",
    bathrooms: "4",
    area: "4x9 sq.ft",
    price: "$2500-$3000",
    image: jphotel2,
  },
  {
    id: 13,
    title: "Ear rings",
    location: "Japan",
    category: "Villa",
    date: "1-10",
    discription: "2776 Green valley, Highland",
    rooms: "3",
    bathrooms: "2",
    area: "5x8 sq.ft",
    price: "$500-$1000",
    image: villa4,
  },
  {
    id: 14,
    title: "Palm Harbor",
    location: "UK",
    category: "Villa",
    date: "10-20",
    discription: "2776 Green valley, Highland",
    rooms: "6",
    bathrooms: "5",
    area: "5x5 sq.ft",
    price: "$2500-$3000",
    image: villa5,
  },
  {
    id: 15,
    title: "Palm Harbor",
    location: "UK",
    category: "House",
    date: "10-20",
    discription: "2776 Green valley, Highland",
    rooms: "9",
    bathrooms: "5",
    area: "5x5 sq.ft",
    price: "$1000-$2000",
    image: home3,
  },
  {
    id: 16,
    location: "US",
    title: "Ear rings",
    category: "House",
    date: "20-31",
    discription: "2776 Green valley, Highland",
    rooms: "2",
    bathrooms: "4",
    area: "8x5 sq.ft",
    price: "$2500-$3000",
    image: home4,
  },
  {
    id: 17,
    location: "US",
    title: "Ear rings",
    category: "Hotel",
    date: "1-10",
    discription: "2776 Green valley, Highland",
    rooms: "8",
    bathrooms: "4",
    area: "8x5 sq.ft",
    price: "$1000-$2000",
    image: hotel4,
  },
  {
    id: 18,
    location: "US",
    title: "Ear rings",
    category: "Hotel",
    date: "20-31",
    discription: "2776 Green valley, Highland",
    rooms: "10",
    bathrooms: "4",
    area: "8x5 sq.ft",
    price: "$2500-$3000",
    image: hotel3,
  },
  {
    id: 19,
    title: "Bavery",
    location: "US",
    category: "House",
    date: "20-31",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 20,
    title: "Bavery",
    location: "US",
    category: "House",
    date: "10-20",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 21,
    location: "US",
    title: "Ear rings",
    category: "Hotel",
    date: "1-10",
    discription: "2776 Green valley, Highland",
    rooms: "5",
    bathrooms: "4",
    area: "8x5 sq.ft",
    price: "$500-$1000",
    image: home2,
  },
  {
    id: 22,
    location: "US",
    title: "Ear rings",
    category: "Hotel",
    date: "10-20",
    discription: "2776 Green valley, Highland",
    rooms: "5",
    bathrooms: "4",
    area: "8x5 sq.ft",
    price: "$500-$1000",
    image: home2,
  },
  {
    id: 23,
    location: "US",
    title: "Ear rings",
    category: "Hotel",
    date: "20-31",
    discription: "2776 Green valley, Highland",
    rooms: "5",
    bathrooms: "4",
    area: "8x5 sq.ft",
    price: "$500-$1000",
    image: home2,
  },
  {
    id: 24,
    location: "US",
    title: "Ear rings",
    category: "Villa",
    date: "20-31",
    discription: "2776 Green valley, Highland",
    rooms: "5",
    bathrooms: "4",
    area: "8x5 sq.ft",
    price: "$500-$1000",
    image: home2,
  },
  {
    id: 25,
    location: "US",
    title: "Ear rings",
    category: "Villa",
    date: "10-20",
    discription: "2776 Green valley, Highland",
    rooms: "5",
    bathrooms: "4",
    area: "8x5 sq.ft",
    price: "$500-$1000",
    image: home2,
  },
  {
    id: 26,
    location: "US",
    title: "Ear rings",
    category: "Villa",
    date: "1-10",
    discription: "2776 Green valley, Highland",
    rooms: "5",
    bathrooms: "4",
    area: "8x5 sq.ft",
    price: "$500-$1000",
    image: home2,
  },
  {
    id: 27,
    title: "Bavery",
    location: "US",
    category: "House",
    date: "1-10",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 28,
    title: "Bavery",
    location: "US",
    category: "House",
    date: "1-10",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$1000-$2000",
    image: home1,
  },
  {
    id: 29,
    title: "Bavery",
    location: "US",
    category: "House",
    date: "1-10",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$2000-$2500",
    image: home1,
  },
  {
    id: 30,
    title: "Bavery",
    location: "US",
    category: "House",
    date: "1-10",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$2500-$3000",
    image: home1,
  },
  {
    id: 31,
    title: "Bavery",
    location: "UK",
    category: "House",
    date: "20-31",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 32,
    title: "Bavery",
    location: "UK",
    category: "House",
    date: "10-20",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 33,
    title: "Bavery",
    location: "UK",
    category: "Hotel",
    date: "10-20",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 34,
    title: "Bavery",
    location: "UK",
    category: "Hotel",
    date: "20-31",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 35,
    title: "Bavery",
    location: "UK",
    category: "Hotel",
    date: "1-10",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 36,
    title: "Bavery",
    location: "UK",
    category: "Villa",
    date: "10-20",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 37,
    title: "Bavery",
    location: "UK",
    category: "Villa",
    date: "1-10",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 38,
    title: "Bavery",
    location: "UK",
    category: "Villa",
    date: "20-31",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$500-$1000",
    image: home1,
  },
  {
    id: 39,
    title: "Bavery",
    location: "UK",
    category: "House",
    date: "1-10",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$2500-$3000",
    image: home1,
  },
  {
    id: 40,
    title: "Bavery",
    location: "UK",
    category: "House",
    date: "1-10",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$1000-$2000",
    image: home1,
  },
  {
    id: 41,
    title: "Bavery",
    location: "UK",
    category: "House",
    date: "1-10",
    discription: "4546 Charch Gate,Londan",
    rooms: "4",
    bathrooms: "2",
    area: "4x5 sq.ft",
    price: "$2000-$2500",
    image: home1,
  },
];
